apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: jubilant-computing-machine
  annotations:
    github.com/project-slug: jdaviscooke/jubilant-computing-machine
spec:
  type: other
  lifecycle: unknown
  owner: team-a
